#!/usr/bin/env python3
"""Check trades for Feb 23, 2026."""
import sqlite3
from datetime import datetime

conn = sqlite3.connect('autotrade.db')
cursor = conn.cursor()

# Get all trades from Feb 23, 2026
cursor.execute('''
    SELECT symbol, direction, entry_price, quantity, status, entry_timestamp, 
           stop_price, target_price, net_pnl
    FROM trades 
    WHERE date(entry_timestamp) = "2026-02-23"
    ORDER BY entry_timestamp
''')

trades = cursor.fetchall()

print("=" * 80)
print("TRADES FOR FEBRUARY 23, 2026 (TODAY)")
print("=" * 80)

if not trades:
    print("\n❌ No trades found for today (Feb 23, 2026)")
    print("\nPossible reasons:")
    print("  1. Trading system not running yet")
    print("  2. No signals generated by strategies")
    print("  3. All signals rejected by cost filter or risk checks")
else:
    print(f"\n✅ Found {len(trades)} trade(s) for today:\n")
    
    for i, trade in enumerate(trades, 1):
        symbol, direction, entry, qty, status, entry_time, sl, target, pnl = trade
        
        print(f"{i}. {symbol:10} {direction:6}")
        print(f"   Entry:  Rs{entry:8.2f} @ {entry_time[:19] if entry_time else 'N/A'}")
        print(f"   Qty:    {qty:3} shares")
        print(f"   SL:     Rs{sl:8.2f}")
        print(f"   Target: Rs{target:8.2f}")
        print(f"   Status: {status}")
        if pnl is not None:
            print(f"   P/L:    Rs{pnl:8.2f}")
        print()

# Check for any recent signals in logs
cursor.execute('''
    SELECT COUNT(*) FROM trades 
    WHERE date(entry_timestamp) >= "2026-02-20"
''')
recent_count = cursor.fetchone()[0]

print("=" * 80)
print(f"Recent trades (since Feb 20): {recent_count}")
print("=" * 80)

conn.close()
